#!/usr/bin/env python3
"""Bake canonical.json into lexicon.js so index.html runs from file:// with no server.

The lexicon is a curated literary corpus; canonical.json remains the single
source of truth. Re-run this whenever canonical.json changes:

    python3 build_lexicon.py
"""
import json

FIELDS = ("word", "gloss", "etymon", "language", "note", "part_of_speech",
          "recovery_type", "image_family", "surprise_score")

def main():
    data = json.load(open("canonical.json"))
    entries = []
    for e in data["entries"]:
        entries.append({k: e.get(k) for k in FIELDS})
        # Derived forms (governor -> government) inherit the parent's etymon,
        # note, and family; they carry their own word, gloss, and part of speech.
        for f in e.get("forms", []):
            form = {k: f.get(k, e.get(k)) for k in FIELDS}
            form["base"] = e["word"]
            if f.get("plural"):
                form["plural"] = f["plural"]
            entries.append(form)
    entries.sort(key=lambda e: e["word"])
    payload = json.dumps(entries, ensure_ascii=False, indent=2)
    banner = ("// GENERATED by build_lexicon.py from canonical.json — do not edit by hand.\n"
              "// Re-run `python3 build_lexicon.py` after changing canonical.json.\n")
    with open("lexicon.js", "w", encoding="utf-8") as f:
        f.write(banner)
        f.write("window.LEXICON = " + payload + ";\n")
    print(f"Wrote lexicon.js with {len(entries)} entries.")

if __name__ == "__main__":
    main()
