// GENERATED by build_lexicon.py from canonical.json — do not edit by hand.
// Re-run `python3 build_lexicon.py` after changing canonical.json.
window.LEXICON = [
  {
    "word": "boy",
    "gloss": null,
    "etymon": null,
    "language": null,
    "note": "Origin uncertain; competing derivations without consensus.",
    "recovery_type": "contested",
    "image_family": "Contested",
    "surprise_score": null
  },
  {
    "word": "bride",
    "gloss": null,
    "etymon": null,
    "language": null,
    "note": "Ultimate origin disputed despite long study.",
    "recovery_type": "contested",
    "image_family": "Contested",
    "surprise_score": null
  },
  {
    "word": "bridegroom",
    "gloss": "bride man",
    "etymon": "brȳdguma",
    "language": "Old English",
    "note": "Modern -groom is folk-etymological.",
    "recovery_type": "literal",
    "image_family": "Kinship",
    "surprise_score": 3
  },
  {
    "word": "calculate",
    "gloss": "count with pebbles",
    "etymon": "calculare",
    "language": "Latin",
    "note": "Using calculi on counting boards.",
    "recovery_type": "conceptual",
    "image_family": "Pebbles",
    "surprise_score": 5
  },
  {
    "word": "calculus",
    "gloss": "little pebble",
    "etymon": "calculus",
    "language": "Latin",
    "note": "Pebble used for reckoning.",
    "recovery_type": "literal",
    "image_family": "Pebbles",
    "surprise_score": 4
  },
  {
    "word": "candid",
    "gloss": "shining white",
    "etymon": "candidus",
    "language": "Latin",
    "note": "Later developed 'frank'.",
    "recovery_type": "literal",
    "image_family": "Law",
    "surprise_score": 4
  },
  {
    "word": "candidate",
    "gloss": "clothed in white",
    "etymon": "candidatus",
    "language": "Latin",
    "note": "White toga of office-seekers.",
    "recovery_type": "conceptual",
    "image_family": "Law",
    "surprise_score": 5
  },
  {
    "word": "daisy",
    "gloss": "day's eye",
    "etymon": "dæges ēage",
    "language": "Old English",
    "note": "Flower opens by day.",
    "recovery_type": "literal",
    "image_family": "Sky",
    "surprise_score": 4
  },
  {
    "word": "disaster",
    "gloss": "ill star",
    "etymon": "disastro",
    "language": "Italian",
    "note": "Attributed to an unfavorable star.",
    "recovery_type": "conceptual",
    "image_family": "Sky",
    "surprise_score": 5
  },
  {
    "word": "earwig",
    "gloss": "ear insect",
    "etymon": "ēarwicga",
    "language": "Old English",
    "note": "Not related to the folk belief.",
    "recovery_type": "literal",
    "image_family": "Animals",
    "surprise_score": 2
  },
  {
    "word": "girl",
    "gloss": null,
    "etymon": null,
    "language": null,
    "note": "Origin uncertain; no scholarly consensus.",
    "recovery_type": "contested",
    "image_family": "Contested",
    "surprise_score": null
  },
  {
    "word": "gospel",
    "gloss": "good news",
    "etymon": "godspell",
    "language": "Old English",
    "note": "Translation of evangelium.",
    "recovery_type": "literal",
    "image_family": "Religion",
    "surprise_score": 3
  },
  {
    "word": "gossip",
    "gloss": "god sibling",
    "etymon": "godsibb",
    "language": "Old English",
    "note": "god + sibb 'kin'.",
    "recovery_type": "literal",
    "image_family": "Kinship",
    "surprise_score": 4
  },
  {
    "word": "holiday",
    "gloss": "holy day",
    "etymon": "hāligdæġ",
    "language": "Old English",
    "note": "Religious feast day.",
    "recovery_type": "literal",
    "image_family": "Religion",
    "surprise_score": 2
  },
  {
    "word": "husband",
    "gloss": "house dweller",
    "etymon": "húsbóndi",
    "language": "Old English (from Old Norse)",
    "note": "hús 'house' + bóndi 'dweller/farmer'.",
    "recovery_type": "literal",
    "image_family": "Bread & household",
    "surprise_score": 3
  },
  {
    "word": "lady",
    "gloss": "loaf kneader",
    "etymon": "hlæfdige",
    "language": "Old English",
    "note": "hlaf 'loaf' + a second element traditionally linked to 'kneader/maker'.",
    "recovery_type": "literal",
    "image_family": "Bread & household",
    "surprise_score": 5
  },
  {
    "word": "lord",
    "gloss": "loaf keeper",
    "etymon": "hlafweard",
    "language": "Old English",
    "note": "hlaf 'loaf' + weard 'keeper'.",
    "recovery_type": "literal",
    "image_family": "Bread & household",
    "surprise_score": 5
  },
  {
    "word": "manufacture",
    "gloss": "make by hand",
    "etymon": "manufactura",
    "language": "Medieval Latin",
    "note": "manu 'by hand' + factura 'making'; originally literal.",
    "recovery_type": "literal",
    "image_family": "Hands",
    "surprise_score": 4
  },
  {
    "word": "manuscript",
    "gloss": "written by hand",
    "etymon": "manuscriptus",
    "language": "Medieval Latin",
    "note": "manu 'by hand' + scriptus 'written'.",
    "recovery_type": "literal",
    "image_family": "Hands",
    "surprise_score": 3
  },
  {
    "word": "marshal",
    "gloss": "horse servant",
    "etymon": "mareschal",
    "language": "Old French",
    "note": "From a Germanic compound (marah 'horse' + skalk 'servant').",
    "recovery_type": "literal",
    "image_family": "Horses",
    "surprise_score": 4
  },
  {
    "word": "mortgage",
    "gloss": "death pledge",
    "etymon": "mort gage",
    "language": "Old French",
    "note": "mort 'dead' + gage 'pledge'.",
    "recovery_type": "literal",
    "image_family": "Law",
    "surprise_score": 5
  },
  {
    "word": "muscle",
    "gloss": "little mouse",
    "etymon": "musculus",
    "language": "Latin",
    "note": "Diminutive of mus 'mouse'.",
    "recovery_type": "literal",
    "image_family": "Animals",
    "surprise_score": 5
  },
  {
    "word": "nightmare",
    "gloss": "night demon",
    "etymon": "night + mare",
    "language": "Old English",
    "note": "mare is a supernatural being that sits on the sleeper's chest.",
    "recovery_type": "literal",
    "image_family": "Religion",
    "surprise_score": 4
  },
  {
    "word": "nostalgia",
    "gloss": "homecoming pain",
    "etymon": "nostalgia",
    "language": "Modern Latin",
    "note": "Greek nostos 'homecoming' + algos 'pain'.",
    "recovery_type": "literal",
    "image_family": "Body",
    "surprise_score": 5
  },
  {
    "word": "nostril",
    "gloss": "nose hole",
    "etymon": "nosþyrl",
    "language": "Old English",
    "note": "nose + hole.",
    "recovery_type": "literal",
    "image_family": "Body",
    "surprise_score": 2
  },
  {
    "word": "orchard",
    "gloss": "wort yard",
    "etymon": "ortġeard",
    "language": "Old English",
    "note": "Enclosed place of plants.",
    "recovery_type": "literal",
    "image_family": "Agriculture",
    "surprise_score": 4
  },
  {
    "word": "pecuniary",
    "gloss": "of cattle",
    "etymon": "pecuniarius",
    "language": "Latin",
    "note": "From pecus 'cattle'; wealth measured in livestock.",
    "recovery_type": "conceptual",
    "image_family": "Cattle",
    "surprise_score": 5
  },
  {
    "word": "salary",
    "gloss": "salt money",
    "etymon": "salarium",
    "language": "Latin",
    "note": "Avoid the 'paid in salt' myth; connected to salt provision/allowance.",
    "recovery_type": "conceptual",
    "image_family": "Salt",
    "surprise_score": 4
  },
  {
    "word": "sheriff",
    "gloss": "shire reeve",
    "etymon": "sċīrġerēfa",
    "language": "Old English",
    "note": "Shire officer.",
    "recovery_type": "literal",
    "image_family": "Law",
    "surprise_score": 3
  },
  {
    "word": "stirrup",
    "gloss": "climbing rope",
    "etymon": "stiġrāp",
    "language": "Old English",
    "note": "stige 'climbing' + rap 'rope'; original mounting strap.",
    "recovery_type": "conceptual",
    "image_family": "Horses",
    "surprise_score": 4
  },
  {
    "word": "window",
    "gloss": "wind eye",
    "etymon": "vindauga",
    "language": "Old Norse",
    "note": "vindr 'wind' + auga 'eye'.",
    "recovery_type": "literal",
    "image_family": "Sky",
    "surprise_score": 5
  }
];
